<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Loan Report - {{ $business_name }}</title>
    <style>
        body { font-family: sans-serif; font-size: 14px; }
        h2 { text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #000; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }

        .print-btn {
            margin: 20px auto;
            display: block;
            padding: 10px 20px;
            font-size: 16px;
            background-color: #4CAF50;
            color: white;
            border: none;
            cursor: pointer;
        }

        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 13px;
        }

        .signature {
            margin-top: 60px;
            text-align: left;
            padding-left: 50px;
            font-size: 13px;
        }

        @media print {
            .print-btn {
                display: none;
            }
        }
    </style>
</head>
<body>
    <button class="print-btn" onclick="window.print()">{{ $business_name }} Loan Management System</button>

    <h2>Active Loan Report</h2>
    <h4 style="text-align:center;">Generated by {{ $business_name }}</h4>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Contact</th>
                <th>Loan Amount</th>
                <th>Repayment Made</th>
                <th>Balance left</th>
                <th>Loan Issuance Date</th>
                <th>Loan Settled Date</th>
                    <th>Loan Status</th>

            </tr>
        </thead>
        <tbody>
            @forelse ($loans as $loan)
                <tr>
                    <td>{{ $loan->id }}</td>
                    <td>{{ $loan->name }}</td>
                    <td>{{ $loan->contact }}</td>
                    <td>{{ number_format($loan->amount, 2) }}</td>
                    <td>Ugx{{ number_format($loan->repayment_made, 2) }}</td>

                    <td>Ugx{{ number_format($loan->balance_left, 2) }}</td>
                    <td>{{ \Carbon\Carbon::parse($loan->loan_date)->format('m/d/Y') }}</td>
                <td>{{ \Carbon\Carbon::parse($loan->created_at)->format('m/d/Y') }}</td>

                    <td>{{ ucfirst($loan->status) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center;">No loan records available.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p><strong>Report generated by:</strong> {{ $business_name }} System administrator</p>
    </div>

    <div class="signature">
        <p>Name: _______________________________</p>
        <p>Signature: _______________________________</p>
        <p>Date: ___________________</p>
    </div>
</body>
</html>
