name: Deploy Laravel App to LoanSystem.great-site.net

on:
  push:
    branches:
      - laravel_Branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Get latest code
        uses: actions/checkout@v4

      - name: 📦 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.upload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /LoanSystem.great-site.net/htdocs/
          timeout: 86400         # 24 hours in seconds
          log-level: standard
